site_name: QubeCL Docs
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.indexes
    # - navigation.footer
    - toc.follow
    - tabs: true
  palette:
    primary: purple
  custom_dir: ppq_theme
extra_css:
  - css/ppq.css
  - https://unpkg.com/katex@0/dist/katex.min.css #for math support
markdown_extensions:
  - toc:
      permalink: true
      # toc_depth: 1
  # Python Markdown Extensions
  -  abbr
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - md_in_html
  - attr_list # permits downoadable files
  #permits mathmatical statements
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
  - table-reader
  - to-pdf: # enable to auto-generate PDF (currently for whole site)  
      ordered_chapter_level: 100
      toc_level: 6
      author: LM
      copyright: ppqSense S.R.L. 2025
      cover_title: QubeCL Laser Driver Manual
      cover_subtitle: Version 5 (2025)
      cover_logo: img/QubeCL_Logo.png
      output_path: downloads/QubeCL_Manual_v5.pdf
      # enabled_if_env: ENABLED_PDF_EXPORT #uncomment to disable PDF generation during development
copyright: Copyright &copy; 2023-2025 PPQSense S.R.L.
extra:
  generator: false # removes made with material for MkDocs from project footer
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ppqsense-s.r.l.

# Site Structure
nav:
  - Home: index.md
  - Qube Manual V5: QubeCL_Manual_v5.md
  - Downloads: downloads.md

# Math Support (KaTeX)
# extra_javascript:
#   - javascripts/katex.js
#   - https://unpkg.com/katex@0/dist/katex.min.js
#   - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
