site_name: QubeCL Docs
copyright: Copyright &copy; 2014-2025 PPQSense S.R.L.
#------------------------------------------#
#-----------Site Structure-----------------#
#------------------------------------------#
nav:
  - Home: index.md
  - Qube Manual V5: QubeCL_Current_Manual/QubeCL_Manual_v5.md
  - Downloads: downloads.md
  # - Tutorial: tutorial/tutorial.md
#------------------------------------------#
#---------------Layout/Design--------------#
#------------------------------------------#
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.indexes
    # - navigation.footer
    - toc.follow
    # - toc.integrate
    - tabs: true
  # palette:
  #   primary: purple
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: ppq_theme
extra:
  generator: false # removes made with material for MkDocs from project footer
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ppqsense-s.r.l.
extra_css:
  - css/ppq.css
  - https://unpkg.com/katex@0/dist/katex.min.css # Math Symbol Support
#------------------------------------------#
#----------Features/Functionality----------#
#------------------------------------------#
markdown_extensions:
  - toc:
      permalink: true
      # toc_depth: 1
  # - image_captions:
  #     numbering: true
  #     caption_top: false
  # - table_captions:
  #     numbering: true
  #     caption_top: false
  # - caption # not sure if neeeded
  - abbr
  - admonition # used to make notes or warning boxes
  - md_in_html
  - attr_list # permits downoadable files
  - def_list
  - footnotes
  - tables
  - mdx_spanner
  - markdown_katex:
      no_inline_svg: true
  - pymdownx.highlight
  - pymdownx.superfences
  # - pymdownx.arithmatex # preserves LaTeX math equations during markdown conversion for use with KaTeX
      # generic: true
      # inline_syntax: ['dollar']
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
#-------------Plugins-------------------#
plugins:
  - offline #this plugin allows site search to work offline, but interferes with instant loading and versioning
  - search
  - autorefs:
      resolve_closest: true
  - table-reader:
      data_path: "docs/"
  - caption
  - table-of-figures: # not yet working
      directive_identifier: 'table-of-figures'
      figure_types:
        - image
        - table
        - mermaid
      # caption_identifier_description_seperator: '\n'
  # - with-pdf # not sure if needed
  - to-pdf: # enable to auto-generate PDF download(currently for whole site)  
      ordered_chapter_level: 100
      toc_level: 6
      author: LM
      copyright: ppqSense S.R.L. 2025
      cover_title: QubeCL Laser Driver Manual
      cover_subtitle: Version 5 (2025)
      cover_logo: img/QubeCL_Logo.png
      output_path: downloads/QubeCL_Manual_Current.pdf
      # enabled_if_env: ENABLED_PDF_EXPORT #uncomment to disable PDF generation during development
